name: Release

permissions:
  contents: write # For creating releases and uploading artifacts
  pull-requests: read # For building changelog from PRs with labels

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04-arm
            target: linux-aarch64
          - runner: ubuntu-24.04
            target: linux-x86_64
          - runner: macos-26
            target: darwin-aarch64
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@b6
        with:
          go-version-file: 'go.mod'

      - name: Run build
        run: make build

      - name: Upload builds
        uses: actions/upload-artifact@v7
        with:
          name: slap-${{ matrix.platform.target }}
          path: slap

  publish:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download builds
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Rename files for publishing
        run: |
          mkdir -p dist
          ls -R artifacts
          cd artifacts

          for file in slap-*/slap; do
              target=$(dirname "$file")
              mv "$file" "../dist/${target}"
          done

      - name: Checksums
        run: |
          cd dist

          sha256sum slap-* > checksums.txt
          cat checksums.txt

      - name: Upload checksums
        uses: actions/upload-artifact@v7
        with:
          name: checksums
          path: dist/checksums.txt

      - name: Build changelog from PRs with labels
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          configuration: ".github/changelog-configuration.json"
          # PreReleases still get a changelog, but the next full release gets a diff since the last full release,
          # combining possible changelogs of all previous PreReleases in between.
          # PreReleases show a partial changelog since last PreRelease.
          # It is assumed that PreReleases have a '-' in their tag name, e.g. 'v1.0.0-alpha.1'.
          # `github.ref` is in the format of 'refs/tags/v1.0.0-alpha.1' for tags.
          ignorePreReleases: "${{ !contains(github.ref, '-') }}"
          outputFile: .github/release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          # It is assumed that PreReleases have a '-' in their tag name, e.g. 'v1.0.0-alpha.1'.
          # `github.ref` is in the format of 'refs/tags/v1.0.0-alpha.1' for tags.
          prerelease: "${{ contains(github.ref, '-') }}"
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: dist/*

